// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Allow-list of read-only server functions the /api/rpc route may run.

import * as m0 from '@/app/(main)/appointments/actions';
import * as m1 from '@/app/(main)/billing/actions';
import * as m2 from '@/app/(main)/billing/bundle-actions';
import * as m3 from '@/app/(main)/billing/combined-actions';
import * as m4 from '@/app/(main)/billing/invoice-edit-actions';
import * as m5 from '@/app/(main)/billing/invoices-screen-actions';
import * as m6 from '@/app/(main)/biometry/actions';
import * as m7 from '@/app/(main)/camps/actions';
import * as m8 from '@/app/(main)/camps/bundle-actions';
import * as m9 from '@/app/(main)/cash-management/actions';
import * as m10 from '@/app/(main)/cash-management/screen-actions';
import * as m11 from '@/app/(main)/consultation/actions';
import * as m12 from '@/app/(main)/counselling/actions';
import * as m13 from '@/app/(main)/credit-notes/actions';
import * as m14 from '@/app/(main)/doctor-dashboard-surgery/actions';
import * as m15 from '@/app/(main)/doctor-dashboard-surgery/combined-actions';
import * as m16 from '@/app/(main)/doctor-dashboard/actions';
import * as m17 from '@/app/(main)/inventory/actions';
import * as m18 from '@/app/(main)/investigation/actions';
import * as m19 from '@/app/(main)/iol-approval/actions';
import * as m20 from '@/app/(main)/iol-approval/combined-actions';
import * as m21 from '@/app/(main)/master-data/actions';
import * as m22 from '@/app/(main)/master-data/bundle-actions';
import * as m23 from '@/app/(main)/medical-fitness/actions';
import * as m24 from '@/app/(main)/opd-procedures/actions';
import * as m25 from '@/app/(main)/opd-procedures/bundle-actions';
import * as m26 from '@/app/(main)/optical/actions';
import * as m27 from '@/app/(main)/optical/book-finalize-actions';
import * as m28 from '@/app/(main)/optical/screens-actions';
import * as m29 from '@/app/(main)/optometry-dashboard/actions';
import * as m30 from '@/app/(main)/optometry-history/actions';
import * as m31 from '@/app/(main)/ot-intraop/actions';
import * as m32 from '@/app/(main)/ot-postop/actions';
import * as m33 from '@/app/(main)/ot-recovery/actions';
import * as m34 from '@/app/(main)/ot-schedule/actions';
import * as m35 from '@/app/(main)/ot-schedule/bundle-actions';
import * as m36 from '@/app/(main)/patient-checkin/bundle-actions';
import * as m37 from '@/app/(main)/patient-timeline/actions';
import * as m38 from '@/app/(main)/patients/actions';
import * as m39 from '@/app/(main)/payments/actions';
import * as m40 from '@/app/(main)/payments/combined-actions';
import * as m41 from '@/app/(main)/payments/payment-edit-actions';
import * as m42 from '@/app/(main)/payments/received-actions';
import * as m43 from '@/app/(main)/pharmacy/actions';
import * as m44 from '@/app/print-templates/actions';
import * as m45 from '@/app/(main)/queue/actions';
import * as m46 from '@/app/(main)/queue/combined-actions';
import * as m47 from '@/app/(main)/surgical-journey/actions';
import * as m48 from '@/app/(main)/surgical-journey/bundle-actions';
import * as m49 from '@/app/(main)/users/actions';
import * as m50 from '@/app/(main)/users/billing-permission-actions';
import * as m51 from '@/app/(main)/visits/actions';
import * as m52 from '@/app/(main)/visits/combined-actions';
import * as m53 from '@/app/(main)/whatsapp/actions';
import * as m54 from '@/app/(main)/workflow-monitor/actions';

export const READS = {
  'appointments.actions.getDoctors': m0.getDoctors,
  'appointments.actions.searchPatientsForBooking': m0.searchPatientsForBooking,
  'billing.actions.getBiometryForBilling': m1.getBiometryForBilling,
  'billing.actions.getInvestigationOrdersForBilling': m1.getInvestigationOrdersForBilling,
  'billing.actions.getInvoiceById': m1.getInvoiceById,
  'billing.actions.getInvoicesForVisit': m1.getInvoicesForVisit,
  'billing.actions.getPackageForBilling': m1.getPackageForBilling,
  'billing.actions.getPendingProcedureBilling': m1.getPendingProcedureBilling,
  'billing.actions.getPrescriptionsForBilling': m1.getPrescriptionsForBilling,
  'billing.actions.getProceduresForBilling': m1.getProceduresForBilling,
  'billing.actions.getSurgeryBillingOptions': m1.getSurgeryBillingOptions,
  'billing.actions.getTodaysInvoicesForModification': m1.getTodaysInvoicesForModification,
  'billing.actions.getVisitsForPatient': m1.getVisitsForPatient,
  'billing.actions.searchInvoices': m1.searchInvoices,
  'billing.actions.searchPatientsForInvoice': m1.searchPatientsForInvoice,
  'billing.bundle-actions.getPendingBillingBundle': m2.getPendingBillingBundle,
  'billing.combined-actions.getNewInvoiceBootstrap': m3.getNewInvoiceBootstrap,
  'billing.combined-actions.getPatientBillingContext': m3.getPatientBillingContext,
  'billing.combined-actions.getPickedVisitContext': m3.getPickedVisitContext,
  'billing.combined-actions.getVisitBillingContext': m3.getVisitBillingContext,
  'billing.invoice-edit-actions.getInvoiceEditContext': m4.getInvoiceEditContext,
  'billing.invoice-edit-actions.getInvoiceHistory': m4.getInvoiceHistory,
  'billing.invoices-screen-actions.getBillingScreenData': m5.getBillingScreenData,
  'billing.invoices-screen-actions.getInvoicePanel': m5.getInvoicePanel,
  'biometry.actions.getBiometryCompletedToday': m6.getBiometryCompletedToday,
  'biometry.actions.getBiometryDetail': m6.getBiometryDetail,
  'biometry.actions.getBiometryHistory': m6.getBiometryHistory,
  'biometry.actions.getBiometryQueue': m6.getBiometryQueue,
  'biometry.actions.getPendingBiometryBilling': m6.getPendingBiometryBilling,
  'camps.actions.getCampEvent': m7.getCampEvent,
  'camps.actions.listCampEvents': m7.listCampEvents,
  'camps.actions.listScreenings': m7.listScreenings,
  'camps.bundle-actions.getCampBundle': m8.getCampBundle,
  'cash-management.actions.getCashCounterForDate': m9.getCashCounterForDate,
  'cash-management.actions.getDailyReport': m9.getDailyReport,
  'cash-management.actions.getSuggestedOpeningBalance': m9.getSuggestedOpeningBalance,
  'cash-management.actions.isTodayOpen': m9.isTodayOpen,
  'cash-management.screen-actions.getPastDayClosing': m10.getPastDayClosing,
  'consultation.actions.getFollowUpContext': m11.getFollowUpContext,
  'counselling.actions.getCaseNotes': m12.getCaseNotes,
  'counselling.actions.getCaseProcedures': m12.getCaseProcedures,
  'counselling.actions.getCounsellingCases': m12.getCounsellingCases,
  'counselling.actions.getCounsellingHistory': m12.getCounsellingHistory,
  'counselling.actions.getCounsellingItems': m12.getCounsellingItems,
  'counselling.actions.getOTAvailability': m12.getOTAvailability,
  'counselling.actions.getPackagesForCase': m12.getPackagesForCase,
  'counselling.actions.getPatientInvoicesForCase': m12.getPatientInvoicesForCase,
  'counselling.actions.getSurgeons': m12.getSurgeons,
  'credit-notes.actions.getCreditNote': m13.getCreditNote,
  'credit-notes.actions.getCreditNoteFormData': m13.getCreditNoteFormData,
  'credit-notes.actions.searchCreditNotes': m13.searchCreditNotes,
  'credit-notes.actions.searchPatientsForCreditNote': m13.searchPatientsForCreditNote,
  'doctor-dashboard-surgery.actions.getSurgeryDashboardActive': m14.getSurgeryDashboardActive,
  'doctor-dashboard-surgery.actions.getSurgeryDashboardDischargedToday': m14.getSurgeryDashboardDischargedToday,
  'doctor-dashboard-surgery.actions.getSurgeryDashboardHistory': m14.getSurgeryDashboardHistory,
  'doctor-dashboard-surgery.actions.getSurgeryDashboardScheduled': m14.getSurgeryDashboardScheduled,
  'doctor-dashboard-surgery.combined-actions.getSurgeryDashboardBundle': m15.getSurgeryDashboardBundle,
  'doctor-dashboard.actions.getDoctorDashboardData': m16.getDoctorDashboardData,
  'doctor-dashboard.actions.getDoctorHistory': m16.getDoctorHistory,
  'inventory.actions.getConsumptionReport': m17.getConsumptionReport,
  'inventory.actions.getDashboardSummary': m17.getDashboardSummary,
  'inventory.actions.getExpiryReport': m17.getExpiryReport,
  'inventory.actions.getInventoryDashboard': m17.getInventoryDashboard,
  'inventory.actions.getItemMovements': m17.getItemMovements,
  'inventory.actions.getPurchaseLines': m17.getPurchaseLines,
  'inventory.actions.getRecentPurchases': m17.getRecentPurchases,
  'inventory.actions.getStockValuationReport': m17.getStockValuationReport,
  'inventory.actions.getTrackedItemsForPicker': m17.getTrackedItemsForPicker,
  'inventory.actions.getUntrackedDrugs': m17.getUntrackedDrugs,
  'inventory.actions.getVendorPurchaseSummary': m17.getVendorPurchaseSummary,
  'inventory.actions.getVendors': m17.getVendors,
  'inventory.actions.searchItemStock': m17.searchItemStock,
  'investigation.actions.getInvestigationComparisonData': m18.getInvestigationComparisonData,
  'investigation.actions.getInvestigationHistory': m18.getInvestigationHistory,
  'investigation.actions.getInvestigationQueue': m18.getInvestigationQueue,
  'investigation.actions.getInvestigationReport': m18.getInvestigationReport,
  'investigation.actions.getPendingInvestigationBilling': m18.getPendingInvestigationBilling,
  'investigation.actions.getTodaysInvestigations': m18.getTodaysInvestigations,
  'investigation.actions.searchPatientsForInvestigation': m18.searchPatientsForInvestigation,
  'iol-approval.actions.getApprovedToday': m19.getApprovedToday,
  'iol-approval.actions.getIolApprovalDetail': m19.getIolApprovalDetail,
  'iol-approval.actions.getIolApprovalHistory': m19.getIolApprovalHistory,
  'iol-approval.actions.getPendingIolApprovals': m19.getPendingIolApprovals,
  'iol-approval.combined-actions.getIolApprovalQueueBundle': m20.getIolApprovalQueueBundle,
  'master-data.actions.getActiveExamOptions': m21.getActiveExamOptions,
  'master-data.actions.getActiveHistoryOptions': m21.getActiveHistoryOptions,
  'master-data.actions.getActiveIolCatalog': m21.getActiveIolCatalog,
  'master-data.actions.getActivePatientInstructionTemplates': m21.getActivePatientInstructionTemplates,
  'master-data.actions.getClinicalObservations': m21.getClinicalObservations,
  'master-data.actions.getDiagnosesMaster': m21.getDiagnosesMaster,
  'master-data.actions.getDosageOptions': m21.getDosageOptions,
  'master-data.actions.getDrugTypes': m21.getDrugTypes,
  'master-data.actions.getDrugs': m21.getDrugs,
  'master-data.actions.getExamOptions': m21.getExamOptions,
  'master-data.actions.getHistoryOptions': m21.getHistoryOptions,
  'master-data.actions.getIolCatalog': m21.getIolCatalog,
  'master-data.actions.getIopMethods': m21.getIopMethods,
  'master-data.actions.getMasterAuditLog': m21.getMasterAuditLog,
  'master-data.actions.getPackageLineItems': m21.getPackageLineItems,
  'master-data.actions.getPackages': m21.getPackages,
  'master-data.actions.getPatientInstructionTemplates': m21.getPatientInstructionTemplates,
  'master-data.actions.getServices': m21.getServices,
  'master-data.actions.getSurgeries': m21.getSurgeries,
  'master-data.actions.getSurgicalConsumablesMaster': m21.getSurgicalConsumablesMaster,
  'master-data.actions.getVendorsMaster': m21.getVendorsMaster,
  'master-data.bundle-actions.getConsultationMastersBundle': m22.getConsultationMastersBundle,
  'master-data.bundle-actions.getPostopReviewMastersBundle': m22.getPostopReviewMastersBundle,
  'medical-fitness.actions.getCurrentDoctorProfile': m23.getCurrentDoctorProfile,
  'medical-fitness.actions.getInvestigationMasterOptions': m23.getInvestigationMasterOptions,
  'medical-fitness.actions.getMedicalFitnessClearedToday': m23.getMedicalFitnessClearedToday,
  'medical-fitness.actions.getMedicalFitnessDetail': m23.getMedicalFitnessDetail,
  'medical-fitness.actions.getMedicalFitnessHistory': m23.getMedicalFitnessHistory,
  'medical-fitness.actions.getMedicalFitnessQueue': m23.getMedicalFitnessQueue,
  'opd-procedures.actions.getCombinedSchedule': m24.getCombinedSchedule,
  'opd-procedures.actions.getDrugCatalogForOpdProcedures': m24.getDrugCatalogForOpdProcedures,
  'opd-procedures.actions.getOpdProcedureHistory': m24.getOpdProcedureHistory,
  'opd-procedures.actions.getOpdProcedureLists': m24.getOpdProcedureLists,
  'opd-procedures.actions.getOpdProcedureMonthSummary': m24.getOpdProcedureMonthSummary,
  'opd-procedures.actions.getPatientOpdProcedureJourney': m24.getPatientOpdProcedureJourney,
  'opd-procedures.actions.getPostProcedurePrescriptions': m24.getPostProcedurePrescriptions,
  'opd-procedures.bundle-actions.getOpdPatientJourneyBundle': m25.getOpdPatientJourneyBundle,
  'opd-procedures.bundle-actions.getPostProcedureRxBundle': m25.getPostProcedureRxBundle,
  'optical.actions.findOpticalSaleByNumber': m26.findOpticalSaleByNumber,
  'optical.actions.getOpticalAdvanceBalance': m26.getOpticalAdvanceBalance,
  'optical.actions.getOpticalCreditNoteRegister': m26.getOpticalCreditNoteRegister,
  'optical.actions.getOpticalPaymentsForCustomer': m26.getOpticalPaymentsForCustomer,
  'optical.actions.getOpticalRefundRegister': m26.getOpticalRefundRegister,
  'optical.actions.getOpticalSaleDetail': m26.getOpticalSaleDetail,
  'optical.actions.getOpticalSalesForCustomer': m26.getOpticalSalesForCustomer,
  'optical.actions.getRecentOpticalAdvances': m26.getRecentOpticalAdvances,
  'optical.actions.getRecentOpticalItemNames': m26.getRecentOpticalItemNames,
  'optical.actions.searchOpticalCustomers': m26.searchOpticalCustomers,
  'optical.book-finalize-actions.getOpticalBookingContext': m27.getOpticalBookingContext,
  'optical.screens-actions.getOpticalBillPanel': m28.getOpticalBillPanel,
  'optical.screens-actions.getOpticalBillsScreen': m28.getOpticalBillsScreen,
  'optical.screens-actions.getOpticalDeletedReceipts': m28.getOpticalDeletedReceipts,
  'optical.screens-actions.getOpticalNewPaymentContext': m28.getOpticalNewPaymentContext,
  'optical.screens-actions.getOpticalPaymentsScreen': m28.getOpticalPaymentsScreen,
  'optical.screens-actions.getOpticalReceiptPanel': m28.getOpticalReceiptPanel,
  'optometry-dashboard.actions.getOptometryDashboardData': m29.getOptometryDashboardData,
  'optometry-history.actions.getAssessmentDetail': m30.getAssessmentDetail,
  'optometry-history.actions.getOptometryHistory': m30.getOptometryHistory,
  'ot-intraop.actions.getCheckinHistory': m31.getCheckinHistory,
  'ot-intraop.actions.getConsumableOptions': m31.getConsumableOptions,
  'ot-intraop.actions.getOTCaseDetail': m31.getOTCaseDetail,
  'ot-intraop.actions.getOTCaseList': m31.getOTCaseList,
  'ot-intraop.actions.getOTIntraopHistory': m31.getOTIntraopHistory,
  'ot-intraop.actions.getSurgeryLandingForPatient': m31.getSurgeryLandingForPatient,
  'ot-postop.actions.getFollowupReviewContext': m32.getFollowupReviewContext,
  'ot-postop.actions.getOpenPostOpEpisodeForPatient': m32.getOpenPostOpEpisodeForPatient,
  'ot-postop.actions.getPostOpCaseList': m32.getPostOpCaseList,
  'ot-postop.actions.getPostOpEpisodeDetail': m32.getPostOpEpisodeDetail,
  'ot-postop.actions.getPostOpHistory': m32.getPostOpHistory,
  'ot-postop.actions.getPostOpTurnedUpToday': m32.getPostOpTurnedUpToday,
  'ot-recovery.actions.getDrugOptions': m33.getDrugOptions,
  'ot-recovery.actions.getMedDosageOptions': m33.getMedDosageOptions,
  'ot-recovery.actions.getRecoveryCaseList': m33.getRecoveryCaseList,
  'ot-recovery.actions.getRecoveryEpisodeDetail': m33.getRecoveryEpisodeDetail,
  'ot-recovery.actions.getRecoveryHistory': m33.getRecoveryHistory,
  'ot-schedule.actions.getOTAvailability': m34.getOTAvailability,
  'ot-schedule.actions.getOTHistory': m34.getOTHistory,
  'ot-schedule.actions.getOTMonthSummary': m34.getOTMonthSummary,
  'ot-schedule.actions.getOTUpcomingWeek': m34.getOTUpcomingWeek,
  'ot-schedule.actions.getPackagesForDirectSurgery': m34.getPackagesForDirectSurgery,
  'ot-schedule.actions.getScheduledOT': m34.getScheduledOT,
  'ot-schedule.actions.getSurgeonsForDirectSurgery': m34.getSurgeonsForDirectSurgery,
  'ot-schedule.actions.searchPatientsForDirectSurgery': m34.searchPatientsForDirectSurgery,
  'ot-schedule.bundle-actions.getOTListBundle': m35.getOTListBundle,
  'patient-checkin.bundle-actions.getCheckinLandingBundle': m36.getCheckinLandingBundle,
  'patient-timeline.actions.getPatientTimeline': m37.getPatientTimeline,
  'patient-timeline.actions.searchPatients': m37.searchPatients,
  'patients.actions.getDuplicatesByMobile': m38.getDuplicatesByMobile,
  'payments.actions.getAdvanceBalance': m39.getAdvanceBalance,
  'payments.actions.getApprovers': m39.getApprovers,
  'payments.actions.getCreditNoteRegister': m39.getCreditNoteRegister,
  'payments.actions.getCurrentBalancesByPatient': m39.getCurrentBalancesByPatient,
  'payments.actions.getInvoicesForCreditNote': m39.getInvoicesForCreditNote,
  'payments.actions.getLedgerHistory': m39.getLedgerHistory,
  'payments.actions.getOutstandingInvoices': m39.getOutstandingInvoices,
  'payments.actions.getPatientById': m39.getPatientById,
  'payments.actions.getPatientLedgerAudit': m39.getPatientLedgerAudit,
  'payments.actions.getPatientPayments': m39.getPatientPayments,
  'payments.actions.getPatientUnifiedLedger': m39.getPatientUnifiedLedger,
  'payments.actions.getPaymentReport': m39.getPaymentReport,
  'payments.actions.getRefundRegister': m39.getRefundRegister,
  'payments.actions.getTodaysVisits': m39.getTodaysVisits,
  'payments.actions.searchPatientsForPayment': m39.searchPatientsForPayment,
  'payments.actions.searchReceipts': m39.searchReceipts,
  'payments.combined-actions.getCollectPaymentBootstrap': m40.getCollectPaymentBootstrap,
  'payments.combined-actions.getPatientPaymentContext': m40.getPatientPaymentContext,
  'payments.payment-edit-actions.getDeletedPayments': m41.getDeletedPayments,
  'payments.payment-edit-actions.getPaymentEditContext': m41.getPaymentEditContext,
  'payments.payment-edit-actions.getPaymentHistory': m41.getPaymentHistory,
  'payments.received-actions.getPaymentsScreenData': m42.getPaymentsScreenData,
  'payments.received-actions.getReceivedPaymentDetail': m42.getReceivedPaymentDetail,
  'pharmacy.actions.getPendingPrescriptionsForFrontOffice': m43.getPendingPrescriptionsForFrontOffice,
  'pharmacy.actions.getPharmacyDashboard': m43.getPharmacyDashboard,
  'pharmacy.actions.getPharmacyHistory': m43.getPharmacyHistory,
  'pharmacy.actions.getPharmacyWorkspace': m43.getPharmacyWorkspace,
  'print-templates.actions.getHospitalSettings': m44.getHospitalSettings,
  'print-templates.actions.getPrintTemplate': m44.getPrintTemplate,
  'print-templates.actions.listPrintTemplates': m44.listPrintTemplates,
  'queue.actions.getPatientFlow': m45.getPatientFlow,
  'queue.actions.getPatientTimeline': m45.getPatientTimeline,
  'queue.actions.getQueues': m45.getQueues,
  'queue.combined-actions.getPatientFlowBundle': m46.getPatientFlowBundle,
  'surgical-journey.actions.getCompletedSurgicalCases': m47.getCompletedSurgicalCases,
  'surgical-journey.actions.getDischargedTodaySurgicalCases': m47.getDischargedTodaySurgicalCases,
  'surgical-journey.actions.getInvestigationOptionsForCase': m47.getInvestigationOptionsForCase,
  'surgical-journey.actions.getSurgicalCaseDetail': m47.getSurgicalCaseDetail,
  'surgical-journey.actions.getSurgicalCaseLists': m47.getSurgicalCaseLists,
  'surgical-journey.actions.getSurgicalEvaluationArrivalsToday': m47.getSurgicalEvaluationArrivalsToday,
  'surgical-journey.actions.getSurgicalTrackArrivalsToday': m47.getSurgicalTrackArrivalsToday,
  'surgical-journey.bundle-actions.getSurgicalCasesBundle': m48.getSurgicalCasesBundle,
  'users.actions.getLoginHistory': m49.getLoginHistory,
  'users.actions.getMyDesignation': m49.getMyDesignation,
  'users.actions.getUsers': m49.getUsers,
  'users.billing-permission-actions.getBillingPermissionMatrix': m50.getBillingPermissionMatrix,
  'visits.actions.getLastVisitInfo': m51.getLastVisitInfo,
  'visits.actions.getPatientById': m51.getPatientById,
  'visits.actions.getSurgeryTypeOptions': m51.getSurgeryTypeOptions,
  'visits.combined-actions.getBookVisitBootstrap': m52.getBookVisitBootstrap,
  'whatsapp.actions.getWhatsAppInbox': m53.getWhatsAppInbox,
  'workflow-monitor.actions.getWorkflowMonitorData': m54.getWorkflowMonitorData,
};
