#!/bin/bash
set -e

# Fix: Puppeteer failed to launch on Vercel (missing libnss3.so) because
# Next.js's build was bundling/stripping @sparticuz/chromium's binary files.
# serverExternalPackages tells Next.js to leave these packages alone.
# Run this from your veda-hmis repo root in Codespaces.

echo "LyoqIEB0eXBlIHtpbXBvcnQoJ25leHQnKS5OZXh0Q29uZmlnfSAqLwpjb25zdCBuZXh0Q29uZmlnID0gewogIC8vIFB1cHBldGVlciArIEBzcGFydGljdXovY2hyb21pdW0gc2hpcCBuYXRpdmUgYmluYXJpZXMgYW5kIGJyb3RsaS1wYWNrZWQKICAvLyBsaWJyYXJ5IGZpbGVzIChlLmcuIGxpYm5zczMuc28pIHRoYXQgTmV4dC5qcydzIHdlYnBhY2sgYnVuZGxpbmcgc3RyaXBzCiAgLy8gb3V0IGlmIGxlZnQgdG8gcHJvY2VzcyB0aGVtIG5vcm1hbGx5LiBNYXJraW5nIHRoZW0gImV4dGVybmFsIiB0ZWxscwogIC8vIE5leHQuanMgdG8gbGVhdmUgdGhlbSBhcyBwbGFpbiBub2RlX21vZHVsZXMgcmVxdWlyZXMgaW5zdGVhZCwgd2hpY2ggaXMKICAvLyByZXF1aXJlZCBmb3IgaGVhZGxlc3MgQ2hyb21lIHRvIGFjdHVhbGx5IGxhdW5jaCBpbiB0aGUgZGVwbG95ZWQKICAvLyBzZXJ2ZXJsZXNzIGZ1bmN0aW9uICh1c2VkIGZvciBpbnZvaWNlIFBERiBnZW5lcmF0aW9uKS4KICBzZXJ2ZXJFeHRlcm5hbFBhY2thZ2VzOiBbJ0BzcGFydGljdXovY2hyb21pdW0nLCAncHVwcGV0ZWVyLWNvcmUnXSwKICBleHBlcmltZW50YWw6IHsKICAgIHNlcnZlckFjdGlvbnM6IHsKICAgICAgLy8gR2l0SHViIENvZGVzcGFjZXMgZm9yd2FyZHMgeW91ciBwb3J0IHRocm91Z2ggYSBwcm94eSBVUkwgbGlrZQogICAgICAvLyBodHRwczovLzxuYW1lPi0zMDAwLmFwcC5naXRodWIuZGV2IC0tIE5leHQuanMncyBTZXJ2ZXIgQWN0aW9ucwogICAgICAvLyBjaGVjayB0aGUgcmVxdWVzdCdzIG9yaWdpbiBhZ2FpbnN0IHRoZSBzZXJ2ZXIncyBob3N0LCBhbmQgdGhpcwogICAgICAvLyB3aWxkY2FyZCB0ZWxscyBpdCB0byB0cnVzdCBDb2Rlc3BhY2VzJyBmb3J3YXJkaW5nIGRvbWFpbnMuCiAgICAgIGFsbG93ZWRPcmlnaW5zOiBbJyouYXBwLmdpdGh1Yi5kZXYnLCAnKi5naXRodWIuZGV2JywgJ2xvY2FsaG9zdDozMDAwJ10sCiAgICB9LAogIH0sCn07Cgptb2R1bGUuZXhwb3J0cyA9IG5leHRDb25maWc7Cgo=" | base64 -d > "next.config.js"
echo "Wrote next.config.js"

git add next.config.js
git commit -m "Fix: externalize @sparticuz/chromium so Vercel build keeps its binary files"
git push

echo "Done. After Vercel redeploys, retest:"
echo "https://portal.vedaeyehospital.com/api/test-invoice-pdf/bf96cb51-46bd-45ad-8562-08665adba446"
