#!/bin/bash
# ============================================================================
# fix_surgery_dashboard_recovery_episodes_shape.sh
#
# Fixes: "(a.recovery_episodes || []).some is not a function" error on the
# Surgery Dashboard's Active tab.
#
# ROOT CAUSE: recovery_episodes.ot_schedule_id has a UNIQUE constraint in
# the database, making it a genuine 1:1 relationship with ot_schedule --
# not 1:many. PostgREST therefore embeds recovery_episodes as a single
# object (or null) when queried from the ot_schedule side, never as an
# array. getSurgeryDashboardActive (in doctor-dashboard-surgery/actions.js)
# incorrectly assumed an array and called .some()/.find() on it, which
# throws the moment any ot_schedule row with status='Completed' actually
# has a recovery episode attached (confirmed against your training data,
# which currently has 6 such cases).
#
# FIX: recovery_episodes is now treated as the single object/null it
# actually is -- no .some()/.find(), just a direct property check.
#
#   MODIFIED: app/(main)/doctor-dashboard-surgery/actions.js
#
# Run this from the root of your veda-hmis repo in GitHub Codespaces.
# ============================================================================

set -e

echo "==> Surgery Dashboard recovery_episodes shape fix"
echo ""

if [ ! -f "package.json" ] || [ ! -d "app" ]; then
  echo "ERROR: This doesn't look like the veda-hmis repo root (no package.json / app dir found)."
  echo "cd into your repo root and re-run this script."
  exit 1
fi

if [ ! -f "app/(main)/doctor-dashboard-surgery/actions.js" ]; then
  echo "ERROR: app/(main)/doctor-dashboard-surgery/actions.js not found."
  echo "This script expects the Surgery Dashboard to already exist."
  exit 1
fi

echo "==> Overwriting app/(main)/doctor-dashboard-surgery/actions.js"
echo "J3VzZSBzZXJ2ZXInOwoKaW1wb3J0IHsgY3JlYXRlQ2xpZW50IH0gZnJvbSAnQC9saWIvc3VwYWJhc2Utc2VydmVyJzsKCi8vIOKUgOKUgCBTVVJHRVJZIERBU0hCT0FSRCAtLSBkb2N0b3ItZmFjaW5nIHZpZXcgb2YgdGhlIHN1cmdpY2FsIHBpcGVsaW5lLAovLyBwYXJhbGxlbCB0byB0aGUgT1BEIERvY3RvciBEYXNoYm9hcmQgYnV0IHNjb3BlZCBlbnRpcmVseSB0bwovLyBvdF9zY2hlZHVsZS9zdXJnaWNhbF9jYXNlcy9yZWNvdmVyeV9lcGlzb2RlcyBpbnN0ZWFkIG9mIHF1ZXVlX2VudHJpZXMuCi8vIE5vdCBzY29wZWQgYnkgc3VyZ2VvbiBmb3Igbm93IChzaW5nbGUtc3VyZ2VvbiBob3NwaXRhbCB0b2RheSkgLS0KLy8gc3VyZ2Vvbl9pZCBpcyBhbHJlYWR5IG9uIG90X3NjaGVkdWxlL3N1cmdpY2FsX2Nhc2VzIHNvIGEgcGVyLWRvY3RvcgovLyBmaWx0ZXIgY2FuIGJlIGFkZGVkIGxhdGVyIHdpdGhvdXQgYSBzY2hlbWEgY2hhbmdlLgovLwovLyBUaHJlZSBidWNrZXRzLCBhbGwgZGVyaXZlZCBmcm9tIGV4aXN0aW5nIHN0YXR1cyBmaWVsZHMgLS0gbm8gbmV3Ci8vICJzdXJnZXJ5IGRhc2hib2FyZCBzdGF0dXMiIGNvbHVtbiwgc28gbm90aGluZyBoZXJlIGNhbiBkcmlmdCBvdXQgb2YKLy8gc3luYyB3aXRoIHdoYXQgUGF0aWVudCBDaGVjay1JbiAvIEludHJhb3AgLyBSZWNvdmVyeSBhbHJlYWR5IHNob3c6Ci8vICAgU2NoZWR1bGVkIC0tIG90X3NjaGVkdWxlLnN0YXR1cyA9ICdTY2hlZHVsZWQnIChhbnkgdXBjb21pbmcgZGF0ZSwKLy8gICAgIG5vdCBqdXN0IHRvZGF5IC0tIGEgZG9jdG9yIHJldmlld2luZyB0aGVpciBzdXJnaWNhbCBsaXN0IHdhbnRzCi8vICAgICB0aGUgZnVsbCB1cGNvbWluZyBwaWN0dXJlLCBub3QganVzdCB0b2RheSdzKS4KLy8gICBBY3RpdmUgICAgLS0gb3Rfc2NoZWR1bGUuc3RhdHVzID0gJ0luIFByb2dyZXNzJyAoY2hlY2tlZCBpbiwgaW4gT1QpCi8vICAgICBPUiBzdGF0dXMgPSAnQ29tcGxldGVkJyB3aXRoIGFuIG9wZW4gcmVjb3ZlcnlfZXBpc29kZQovLyAgICAgKGRpc2NoYXJnZV9kYXRlIElTIE5VTEwpIC0tIHN1cmdlcnkgaXMgZG9uZSBidXQgdGhlIHBhdGllbnQKLy8gICAgIGhhc24ndCBiZWVuIGRpc2NoYXJnZWQgZnJvbSBSZWNvdmVyeSB5ZXQuCi8vICAgSGlzdG9yeSAgIC0tIHJlY292ZXJ5X2VwaXNvZGVzLmRpc2NoYXJnZV9kYXRlIElTIE5PVCBOVUxMLiBUaGlzIGlzCi8vICAgICB0aGUgc2luZ2xlIGNvbXBsZXRpb24gc2lnbmFsIC0tIG1hdGNoZXMgdGhlIGZpeCBhbHJlYWR5IGluIHBsYWNlCi8vICAgICBmb3IgUmVjb3ZlcnkvU3VyZ2ljYWwgSm91cm5leSAoZnV0dXJlLWRhdGVkIGRpc2NoYXJnZV9kYXRlIGJ1ZykuCgpjb25zdCBDQVNFX1NFTEVDVCA9ICcqLCBtYXN0ZXJfb3Rfc2Vzc2lvbnMobmFtZSksIHN1cmdpY2FsX2Nhc2VzKGlkLCBzdXJnZXJ5X2NvZGUsIHByb2NlZHVyZV9uYW1lLCBleWUsIHBhdGllbnRfaWQsIHBhdGllbnRzOnBhdGllbnRfaWQoZmlyc3RfbmFtZSwgbGFzdF9uYW1lLCB1aGlkLCBhZ2UsIGdlbmRlciksIHByb2ZpbGVzOnN1cmdlb25faWQoZnVsbF9uYW1lKSknOwoKLy8gRXZlcnkgZnVuY3Rpb24gYmVsb3cgcmV0dXJucyB7IHJvd3MsIGVycm9yIH0gaW5zdGVhZCBvZiBhIGJhcmUgYXJyYXkKLy8gb3IgdGhyb3dpbmcgLS0gYSB0aHJvd24vcmVqZWN0ZWQgcHJvbWlzZSBmcm9tIGEgU2VydmVyIEFjdGlvbiBsZWF2ZXMKLy8gdGhlIGNhbGxpbmcgY2xpZW50J3MgUHJvbWlzZS5hbGwoKSBwZXJtYW5lbnRseSB1bnNldHRsZWQgKG5vIGRhdGEsCi8vIG5vIGVycm9yLCB0aGUgVUkganVzdCBzaXRzIG9uICJMb2FkaW5nLi4uIiBmb3JldmVyIHdpdGggbm90aGluZyBpbgovLyB0aGUgY29uc29sZSB0byBleHBsYWluIHdoeSkuIENhdGNoaW5nIGV2ZXJ5dGhpbmcgaGVyZSBhbmQgaGFuZGluZwovLyBiYWNrIGEgcGxhaW4gZXJyb3Igc3RyaW5nIGxldHMgdGhlIGRhc2hib2FyZCBhY3R1YWxseSBzaG93IHdoYXQgd2VudAovLyB3cm9uZyBpbnN0ZWFkIG9mIGhhbmdpbmcuCgpleHBvcnQgYXN5bmMgZnVuY3Rpb24gZ2V0U3VyZ2VyeURhc2hib2FyZFNjaGVkdWxlZCgpIHsKICB0cnkgewogICAgY29uc3Qgc3VwYWJhc2UgPSBhd2FpdCBjcmVhdGVDbGllbnQoKTsKICAgIGNvbnN0IHRvZGF5SXN0ID0gbmV3IERhdGUoKS50b0xvY2FsZURhdGVTdHJpbmcoJ2VuLUNBJywgeyB0aW1lWm9uZTogJ0FzaWEvS29sa2F0YScgfSk7CiAgICBjb25zdCB7IGRhdGEsIGVycm9yIH0gPSBhd2FpdCBzdXBhYmFzZQogICAgICAuZnJvbSgnb3Rfc2NoZWR1bGUnKQogICAgICAuc2VsZWN0KENBU0VfU0VMRUNUKQogICAgICAuZXEoJ3N0YXR1cycsICdTY2hlZHVsZWQnKQogICAgICAuZ3RlKCdzY2hlZHVsZWRfZGF0ZScsIHRvZGF5SXN0KQogICAgICAub3JkZXIoJ3NjaGVkdWxlZF9kYXRlJywgeyBhc2NlbmRpbmc6IHRydWUgfSkKICAgICAgLm9yZGVyKCdzZXF1ZW5jZV9udW1iZXInLCB7IGFzY2VuZGluZzogdHJ1ZSwgbnVsbHNGaXJzdDogZmFsc2UgfSk7CiAgICBpZiAoZXJyb3IpIHJldHVybiB7IHJvd3M6IFtdLCBlcnJvcjogZXJyb3IubWVzc2FnZSB9OwogICAgcmV0dXJuIHsgcm93czogKGRhdGEgfHwgW10pLmZpbHRlcigoYikgPT4gYi5zdXJnaWNhbF9jYXNlcyksIGVycm9yOiBudWxsIH07CiAgfSBjYXRjaCAoZSkgewogICAgcmV0dXJuIHsgcm93czogW10sIGVycm9yOiBlPy5tZXNzYWdlIHx8ICdVbmtub3duIGVycm9yIGxvYWRpbmcgU2NoZWR1bGVkIHN1cmdlcmllcy4nIH07CiAgfQp9CgpleHBvcnQgYXN5bmMgZnVuY3Rpb24gZ2V0U3VyZ2VyeURhc2hib2FyZEFjdGl2ZSgpIHsKICB0cnkgewogICAgY29uc3Qgc3VwYWJhc2UgPSBhd2FpdCBjcmVhdGVDbGllbnQoKTsKCiAgICBjb25zdCBbeyBkYXRhOiBpblByb2dyZXNzLCBlcnJvcjogaW5Qcm9ncmVzc0Vycm9yIH0sIHsgZGF0YTogY29tcGxldGVkLCBlcnJvcjogY29tcGxldGVkRXJyb3IgfV0gPSBhd2FpdCBQcm9taXNlLmFsbChbCiAgICAgIHN1cGFiYXNlCiAgICAgICAgLmZyb20oJ290X3NjaGVkdWxlJykKICAgICAgICAuc2VsZWN0KENBU0VfU0VMRUNUKQogICAgICAgIC5lcSgnc3RhdHVzJywgJ0luIFByb2dyZXNzJykKICAgICAgICAub3JkZXIoJ3NjaGVkdWxlZF9kYXRlJywgeyBhc2NlbmRpbmc6IHRydWUgfSksCiAgICAgIHN1cGFiYXNlCiAgICAgICAgLmZyb20oJ290X3NjaGVkdWxlJykKICAgICAgICAuc2VsZWN0KGAke0NBU0VfU0VMRUNUfSwgcmVjb3ZlcnlfZXBpc29kZXMoaWQsIGRpc2NoYXJnZV9kYXRlKWApCiAgICAgICAgLmVxKCdzdGF0dXMnLCAnQ29tcGxldGVkJykKICAgICAgICAub3JkZXIoJ3NjaGVkdWxlZF9kYXRlJywgeyBhc2NlbmRpbmc6IGZhbHNlIH0pLAogICAgXSk7CiAgICBpZiAoaW5Qcm9ncmVzc0Vycm9yIHx8IGNvbXBsZXRlZEVycm9yKSByZXR1cm4geyByb3dzOiBbXSwgZXJyb3I6IChpblByb2dyZXNzRXJyb3IgfHwgY29tcGxldGVkRXJyb3IpLm1lc3NhZ2UgfTsKCiAgICAvLyByZWNvdmVyeV9lcGlzb2Rlcy5vdF9zY2hlZHVsZV9pZCBpcyBVTklRVUUsIHNvIHRoaXMgaXMgYSAxOjEKICAgIC8vIHJlbGF0aW9uc2hpcCAtLSBQb3N0Z1JFU1QgZW1iZWRzIGl0IGFzIGEgc2luZ2xlIG9iamVjdCAob3IgbnVsbCksCiAgICAvLyBuZXZlciBhbiBhcnJheSwgbm8gbWF0dGVyIHdoaWNoIHNpZGUgdGhlIGVtYmVkIGlzIHJlcXVlc3RlZCBmcm9tLgogICAgY29uc3QgaW5SZWNvdmVyeSA9IChjb21wbGV0ZWQgfHwgW10pLmZpbHRlcigoYikgPT4gYi5zdXJnaWNhbF9jYXNlcyAmJiBiLnJlY292ZXJ5X2VwaXNvZGVzICYmICFiLnJlY292ZXJ5X2VwaXNvZGVzLmRpc2NoYXJnZV9kYXRlKTsKICAgIGNvbnN0IHN0YWdlID0gKGIpID0+IChiLnN0YXR1cyA9PT0gJ0luIFByb2dyZXNzJyA/ICdDaGVja2VkLUluIC8gSW4gT1QnIDogJ0luIFJlY292ZXJ5Jyk7CgogICAgY29uc3Qgcm93cyA9IFsKICAgICAgLi4uKGluUHJvZ3Jlc3MgfHwgW10pLmZpbHRlcigoYikgPT4gYi5zdXJnaWNhbF9jYXNlcykubWFwKChiKSA9PiAoeyAuLi5iLCBzdGFnZTogc3RhZ2UoYikgfSkpLAogICAgICAuLi5pblJlY292ZXJ5Lm1hcCgoYikgPT4gKHsgLi4uYiwgc3RhZ2U6IHN0YWdlKGIpLCByZWNvdmVyeUVwaXNvZGVJZDogYi5yZWNvdmVyeV9lcGlzb2Rlcz8uaWQgfSkpLAogICAgXTsKICAgIHJldHVybiB7IHJvd3MsIGVycm9yOiBudWxsIH07CiAgfSBjYXRjaCAoZSkgewogICAgcmV0dXJuIHsgcm93czogW10sIGVycm9yOiBlPy5tZXNzYWdlIHx8ICdVbmtub3duIGVycm9yIGxvYWRpbmcgQWN0aXZlIHN1cmdlcmllcy4nIH07CiAgfQp9CgpleHBvcnQgYXN5bmMgZnVuY3Rpb24gZ2V0U3VyZ2VyeURhc2hib2FyZEhpc3RvcnkoKSB7CiAgdHJ5IHsKICAgIGNvbnN0IHN1cGFiYXNlID0gYXdhaXQgY3JlYXRlQ2xpZW50KCk7CiAgICBjb25zdCB7IGRhdGEsIGVycm9yIH0gPSBhd2FpdCBzdXBhYmFzZQogICAgICAuZnJvbSgncmVjb3ZlcnlfZXBpc29kZXMnKQogICAgICAuc2VsZWN0KCdpZCwgZGlzY2hhcmdlX2RhdGUsIG90X3NjaGVkdWxlX2lkLCBzdXJnaWNhbF9jYXNlcyhpZCwgc3VyZ2VyeV9jb2RlLCBwcm9jZWR1cmVfbmFtZSwgZXllLCBwYXRpZW50czpwYXRpZW50X2lkKGZpcnN0X25hbWUsIGxhc3RfbmFtZSwgdWhpZCwgYWdlLCBnZW5kZXIpLCBwcm9maWxlczpzdXJnZW9uX2lkKGZ1bGxfbmFtZSkpJykKICAgICAgLm5vdCgnZGlzY2hhcmdlX2RhdGUnLCAnaXMnLCBudWxsKQogICAgICAub3JkZXIoJ2Rpc2NoYXJnZV9kYXRlJywgeyBhc2NlbmRpbmc6IGZhbHNlIH0pCiAgICAgIC5saW1pdCgyMDApOwogICAgaWYgKGVycm9yKSByZXR1cm4geyByb3dzOiBbXSwgZXJyb3I6IGVycm9yLm1lc3NhZ2UgfTsKICAgIHJldHVybiB7IHJvd3M6IChkYXRhIHx8IFtdKS5maWx0ZXIoKGUpID0+IGUuc3VyZ2ljYWxfY2FzZXMpLCBlcnJvcjogbnVsbCB9OwogIH0gY2F0Y2ggKGUpIHsKICAgIHJldHVybiB7IHJvd3M6IFtdLCBlcnJvcjogZT8ubWVzc2FnZSB8fCAnVW5rbm93biBlcnJvciBsb2FkaW5nIHN1cmdlcnkgSGlzdG9yeS4nIH07CiAgfQp9Cg==" | base64 -d > "app/(main)/doctor-dashboard-surgery/actions.js"

echo ""
echo "==> File written. Verifying build..."
if command -v npm >/dev/null 2>&1; then
  npm run build || { echo "BUILD FAILED -- check output above before pushing."; exit 1; }
else
  echo "npm not found -- skipping build verification, run 'npm run build' manually."
fi

echo ""
echo "==> Done. Review changes with: git status && git diff"
echo "==> To deploy, run:"
echo "    git add -A"
echo '    git commit -m "Fix Surgery Dashboard: recovery_episodes is a 1:1 object, not an array"'
echo "    git push"
