// Browser side of parallel reads.
//
// Next.js runs every server action from a page strictly one at a time,
// so a screen's loads (and a dashboard's 15-second refresh) queued up
// behind each other and behind clicks. Read-only functions are instead
// called through /api/rpc with a plain fetch, which the browser runs in
// parallel. Saves still go through server actions, unchanged.
//
// Results of the SAME function are handed back in the order they were
// asked for (the requests themselves still run in parallel). That keeps
// the old behaviour where a later search or refresh can never be
// overwritten by an earlier, slower one.
//
// The per-function wrappers in lib/rpc-reads/ are generated by
// tools/parallel-reads/generate.js -- don't edit those by hand.

import { encode, decode } from './rpcCodec';

const lastByName = new Map();

async function send(name, args) {
  const res = await fetch(`/api/rpc/${name}`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    credentials: 'same-origin',
    cache: 'no-store',
    body: JSON.stringify(encode(args)),
  });
  if (res.status === 401) {
    // Session is gone (logged out elsewhere, or expired) -- same outcome
    // as a server action hitting the login redirect.
    if (typeof window !== 'undefined') window.location.href = '/login';
    throw new Error('Your session has ended. Please log in again.');
  }
  let body = null;
  try { body = await res.json(); } catch { /* fall through */ }
  if (!res.ok || !body || !('r' in body)) {
    throw new Error(body?.error || 'Could not load data -- check your connection and try again.');
  }
  return decode(body.r);
}

export function rpcCall(name, args) {
  const request = send(name, args);
  request.catch(() => {}); // the caller handles it via `ordered`; avoid a spurious console warning
  const previous = lastByName.get(name);
  const ordered = previous ? previous.then(() => request) : request;
  const settled = ordered.then(() => {}, () => {});
  lastByName.set(name, settled);
  settled.then(() => { if (lastByName.get(name) === settled) lastByName.delete(name); });
  return ordered;
}
