// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/appointments/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getDoctors = (...args) => rpcCall('appointments.actions.getDoctors', args);
export const searchPatientsForBooking = (...args) => rpcCall('appointments.actions.searchPatientsForBooking', args);
