// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/billing/combined-actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getNewInvoiceBootstrap = (...args) => rpcCall('billing.combined-actions.getNewInvoiceBootstrap', args);
export const getPatientBillingContext = (...args) => rpcCall('billing.combined-actions.getPatientBillingContext', args);
export const getPickedVisitContext = (...args) => rpcCall('billing.combined-actions.getPickedVisitContext', args);
export const getVisitBillingContext = (...args) => rpcCall('billing.combined-actions.getVisitBillingContext', args);
