// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/billing/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getBiometryForBilling = (...args) => rpcCall('billing.actions.getBiometryForBilling', args);
export const getInvestigationOrdersForBilling = (...args) => rpcCall('billing.actions.getInvestigationOrdersForBilling', args);
export const getInvoiceById = (...args) => rpcCall('billing.actions.getInvoiceById', args);
export const getInvoicesForVisit = (...args) => rpcCall('billing.actions.getInvoicesForVisit', args);
export const getPackageForBilling = (...args) => rpcCall('billing.actions.getPackageForBilling', args);
export const getPendingProcedureBilling = (...args) => rpcCall('billing.actions.getPendingProcedureBilling', args);
export const getPrescriptionsForBilling = (...args) => rpcCall('billing.actions.getPrescriptionsForBilling', args);
export const getProceduresForBilling = (...args) => rpcCall('billing.actions.getProceduresForBilling', args);
export const getSurgeryBillingOptions = (...args) => rpcCall('billing.actions.getSurgeryBillingOptions', args);
export const getTodaysInvoicesForModification = (...args) => rpcCall('billing.actions.getTodaysInvoicesForModification', args);
export const getVisitsForPatient = (...args) => rpcCall('billing.actions.getVisitsForPatient', args);
export const searchInvoices = (...args) => rpcCall('billing.actions.searchInvoices', args);
export const searchPatientsForInvoice = (...args) => rpcCall('billing.actions.searchPatientsForInvoice', args);
