// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/biometry/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getBiometryCompletedToday = (...args) => rpcCall('biometry.actions.getBiometryCompletedToday', args);
export const getBiometryDetail = (...args) => rpcCall('biometry.actions.getBiometryDetail', args);
export const getBiometryHistory = (...args) => rpcCall('biometry.actions.getBiometryHistory', args);
export const getBiometryQueue = (...args) => rpcCall('biometry.actions.getBiometryQueue', args);
export const getPendingBiometryBilling = (...args) => rpcCall('biometry.actions.getPendingBiometryBilling', args);
