// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/camps/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getCampEvent = (...args) => rpcCall('camps.actions.getCampEvent', args);
export const listCampEvents = (...args) => rpcCall('camps.actions.listCampEvents', args);
export const listScreenings = (...args) => rpcCall('camps.actions.listScreenings', args);
