// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/consultation/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getFollowUpContext = (...args) => rpcCall('consultation.actions.getFollowUpContext', args);
