// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/counselling/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getCaseNotes = (...args) => rpcCall('counselling.actions.getCaseNotes', args);
export const getCaseProcedures = (...args) => rpcCall('counselling.actions.getCaseProcedures', args);
export const getCounsellingCases = (...args) => rpcCall('counselling.actions.getCounsellingCases', args);
export const getCounsellingHistory = (...args) => rpcCall('counselling.actions.getCounsellingHistory', args);
export const getCounsellingItems = (...args) => rpcCall('counselling.actions.getCounsellingItems', args);
export const getOTAvailability = (...args) => rpcCall('counselling.actions.getOTAvailability', args);
export const getPackagesForCase = (...args) => rpcCall('counselling.actions.getPackagesForCase', args);
export const getPatientInvoicesForCase = (...args) => rpcCall('counselling.actions.getPatientInvoicesForCase', args);
export const getSurgeons = (...args) => rpcCall('counselling.actions.getSurgeons', args);
