// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/investigation/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getInvestigationComparisonData = (...args) => rpcCall('investigation.actions.getInvestigationComparisonData', args);
export const getInvestigationHistory = (...args) => rpcCall('investigation.actions.getInvestigationHistory', args);
export const getInvestigationQueue = (...args) => rpcCall('investigation.actions.getInvestigationQueue', args);
export const getInvestigationReport = (...args) => rpcCall('investigation.actions.getInvestigationReport', args);
export const getPendingInvestigationBilling = (...args) => rpcCall('investigation.actions.getPendingInvestigationBilling', args);
export const getTodaysInvestigations = (...args) => rpcCall('investigation.actions.getTodaysInvestigations', args);
export const searchPatientsForInvestigation = (...args) => rpcCall('investigation.actions.searchPatientsForInvestigation', args);
