// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/inventory/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getConsumptionReport = (...args) => rpcCall('inventory.actions.getConsumptionReport', args);
export const getDashboardSummary = (...args) => rpcCall('inventory.actions.getDashboardSummary', args);
export const getExpiryReport = (...args) => rpcCall('inventory.actions.getExpiryReport', args);
export const getInventoryDashboard = (...args) => rpcCall('inventory.actions.getInventoryDashboard', args);
export const getItemMovements = (...args) => rpcCall('inventory.actions.getItemMovements', args);
export const getPurchaseLines = (...args) => rpcCall('inventory.actions.getPurchaseLines', args);
export const getRecentPurchases = (...args) => rpcCall('inventory.actions.getRecentPurchases', args);
export const getStockValuationReport = (...args) => rpcCall('inventory.actions.getStockValuationReport', args);
export const getTrackedItemsForPicker = (...args) => rpcCall('inventory.actions.getTrackedItemsForPicker', args);
export const getUntrackedDrugs = (...args) => rpcCall('inventory.actions.getUntrackedDrugs', args);
export const getVendorPurchaseSummary = (...args) => rpcCall('inventory.actions.getVendorPurchaseSummary', args);
export const getVendors = (...args) => rpcCall('inventory.actions.getVendors', args);
export const searchItemStock = (...args) => rpcCall('inventory.actions.searchItemStock', args);
