// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/optical/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const findOpticalSaleByNumber = (...args) => rpcCall('optical.actions.findOpticalSaleByNumber', args);
export const getOpenOpticalOrders = (...args) => rpcCall('optical.actions.getOpenOpticalOrders', args);
export const getOpticalAdvanceBalance = (...args) => rpcCall('optical.actions.getOpticalAdvanceBalance', args);
export const getOpticalCreditNoteRegister = (...args) => rpcCall('optical.actions.getOpticalCreditNoteRegister', args);
export const getOpticalDashboardSummary = (...args) => rpcCall('optical.actions.getOpticalDashboardSummary', args);
export const getOpticalPaymentEditHistory = (...args) => rpcCall('optical.actions.getOpticalPaymentEditHistory', args);
export const getOpticalPaymentsForCustomer = (...args) => rpcCall('optical.actions.getOpticalPaymentsForCustomer', args);
export const getOpticalPaymentsRegister = (...args) => rpcCall('optical.actions.getOpticalPaymentsRegister', args);
export const getOpticalRefundRegister = (...args) => rpcCall('optical.actions.getOpticalRefundRegister', args);
export const getOpticalSaleDetail = (...args) => rpcCall('optical.actions.getOpticalSaleDetail', args);
export const getOpticalSaleEditHistory = (...args) => rpcCall('optical.actions.getOpticalSaleEditHistory', args);
export const getOpticalSalesForCustomer = (...args) => rpcCall('optical.actions.getOpticalSalesForCustomer', args);
export const getOutstandingOpticalBills = (...args) => rpcCall('optical.actions.getOutstandingOpticalBills', args);
export const getRecentOpticalAdvances = (...args) => rpcCall('optical.actions.getRecentOpticalAdvances', args);
export const getRecentOpticalItemNames = (...args) => rpcCall('optical.actions.getRecentOpticalItemNames', args);
export const searchOpticalCustomers = (...args) => rpcCall('optical.actions.searchOpticalCustomers', args);
export const searchOpticalSaleHistory = (...args) => rpcCall('optical.actions.searchOpticalSaleHistory', args);
