// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/optical/screens-actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getOpticalBillPanel = (...args) => rpcCall('optical.screens-actions.getOpticalBillPanel', args);
export const getOpticalBillsScreen = (...args) => rpcCall('optical.screens-actions.getOpticalBillsScreen', args);
export const getOpticalDeletedReceipts = (...args) => rpcCall('optical.screens-actions.getOpticalDeletedReceipts', args);
export const getOpticalNewPaymentContext = (...args) => rpcCall('optical.screens-actions.getOpticalNewPaymentContext', args);
export const getOpticalPaymentsScreen = (...args) => rpcCall('optical.screens-actions.getOpticalPaymentsScreen', args);
export const getOpticalReceiptPanel = (...args) => rpcCall('optical.screens-actions.getOpticalReceiptPanel', args);
