// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/optometry/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getLatestGlassesPrescription = (...args) => rpcCall('optometry.actions.getLatestGlassesPrescription', args);
