// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/patients/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getDuplicatesByMobile = (...args) => rpcCall('patients.actions.getDuplicatesByMobile', args);
