// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/payments/received-actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getPaymentsScreenData = (...args) => rpcCall('payments.received-actions.getPaymentsScreenData', args);
export const getReceivedPaymentDetail = (...args) => rpcCall('payments.received-actions.getReceivedPaymentDetail', args);
