// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/payments/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getAdvanceBalance = (...args) => rpcCall('payments.actions.getAdvanceBalance', args);
export const getApprovers = (...args) => rpcCall('payments.actions.getApprovers', args);
export const getCreditNoteRegister = (...args) => rpcCall('payments.actions.getCreditNoteRegister', args);
export const getCurrentBalancesByPatient = (...args) => rpcCall('payments.actions.getCurrentBalancesByPatient', args);
export const getInvoicesForCreditNote = (...args) => rpcCall('payments.actions.getInvoicesForCreditNote', args);
export const getLedgerHistory = (...args) => rpcCall('payments.actions.getLedgerHistory', args);
export const getOutstandingInvoices = (...args) => rpcCall('payments.actions.getOutstandingInvoices', args);
export const getPatientById = (...args) => rpcCall('payments.actions.getPatientById', args);
export const getPatientLedgerAudit = (...args) => rpcCall('payments.actions.getPatientLedgerAudit', args);
export const getPatientPayments = (...args) => rpcCall('payments.actions.getPatientPayments', args);
export const getPatientUnifiedLedger = (...args) => rpcCall('payments.actions.getPatientUnifiedLedger', args);
export const getPaymentReport = (...args) => rpcCall('payments.actions.getPaymentReport', args);
export const getRefundRegister = (...args) => rpcCall('payments.actions.getRefundRegister', args);
export const getTodaysVisits = (...args) => rpcCall('payments.actions.getTodaysVisits', args);
export const searchPatientsForPayment = (...args) => rpcCall('payments.actions.searchPatientsForPayment', args);
export const searchReceipts = (...args) => rpcCall('payments.actions.searchReceipts', args);
