// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/payments/combined-actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getCollectPaymentBootstrap = (...args) => rpcCall('payments.combined-actions.getCollectPaymentBootstrap', args);
export const getPatientPaymentContext = (...args) => rpcCall('payments.combined-actions.getPatientPaymentContext', args);
