// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/pharmacy/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getPendingPrescriptionsForFrontOffice = (...args) => rpcCall('pharmacy.actions.getPendingPrescriptionsForFrontOffice', args);
export const getPharmacyDashboard = (...args) => rpcCall('pharmacy.actions.getPharmacyDashboard', args);
export const getPharmacyHistory = (...args) => rpcCall('pharmacy.actions.getPharmacyHistory', args);
export const getPharmacyWorkspace = (...args) => rpcCall('pharmacy.actions.getPharmacyWorkspace', args);
