// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/queue/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getPatientFlow = (...args) => rpcCall('queue.actions.getPatientFlow', args);
export const getPatientTimeline = (...args) => rpcCall('queue.actions.getPatientTimeline', args);
export const getQueues = (...args) => rpcCall('queue.actions.getQueues', args);
