// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/queue/combined-actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getPatientFlowBundle = (...args) => rpcCall('queue.combined-actions.getPatientFlowBundle', args);
