// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/users/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getLoginHistory = (...args) => rpcCall('users.actions.getLoginHistory', args);
export const getMyDesignation = (...args) => rpcCall('users.actions.getMyDesignation', args);
export const getUsers = (...args) => rpcCall('users.actions.getUsers', args);
