// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/visits/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getLastVisitInfo = (...args) => rpcCall('visits.actions.getLastVisitInfo', args);
export const getPatientById = (...args) => rpcCall('visits.actions.getPatientById', args);
export const getSurgeryTypeOptions = (...args) => rpcCall('visits.actions.getSurgeryTypeOptions', args);
