// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/visits/combined-actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getBookVisitBootstrap = (...args) => rpcCall('visits.combined-actions.getBookVisitBootstrap', args);
