// GENERATED by tools/parallel-reads/generate.js -- do not edit by hand.
// Browser wrappers for read-only functions in app/(main)/whatsapp/actions.js.
import { rpcCall } from '@/lib/rpcClient';

export const getWhatsAppInbox = (...args) => rpcCall('whatsapp.actions.getWhatsAppInbox', args);
